name: xteve
base: core20 # the base snap is the execution environment for this snap
summary: M3U Proxy for Plex DVR and Emby Live TV.
adopt-info: xteve
description: |
  xTeVe emulates a DVR tuner for Plex and Emby. It takes an M3U files and
  emulates a network tuner that can be discovered by those services. Provides
  multiple tuners and caching proxy of streams. Can also take XMLTV files an
  handle them internally for program guides.

grade: stable
confinement: strict

parts:
  xteve:
    plugin: go
    source: .
    override-stage: |
      snapcraftctl stage
      snapcraftctl set-version `$SNAPCRAFT_STAGE/bin/xteve -version`

apps:
  xteve:
    daemon: simple
    command: bin/xteve -port 8080 -config $SNAP_COMMON/config -no-updates
    plugs:
      - network
      - network-bind
  inactive:
    command: bin/xteve-inactive -port 8080
    plugs:
      - network

hooks:
  pre-refresh: 
    plugs:
      - network
