name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'
      - name: Build project
        run: go build ./...
      # Add build steps here
      # For example:
      # - name: Build project
      #   run: go build ./...

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'
      - name: Run tests
        run: go test ./...
      # Add test steps here
      # For example:
      # - name: Run tests
      #   run: go test ./...

  lint:
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Run golangci-lint
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          golangci-lint run
      # Add linting steps here
      # For example:
      # - name: Lint code
      #   run: golangci-lint run

  snap-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install snapcraft and lxd
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm
          sudo snap install snapcraft --classic
          sudo snap install lxd
      - name: Initialize LXD
        run: sudo lxd init --auto
      - name: Add user to lxd group
        run: |
          sudo groupadd --system lxd || true
          sudo usermod -a -G lxd $USER || true
          # The new session part is tricky in CI. sg lxd -c "command" will be used later for snapcraft.
          # Re-login or newgrp is not feasible in most CI script flows.
          # We rely on `sg lxd -c "snapcraft"` for the build step to use the new group membership.
      - name: Build the snap
        run: sg lxd -c "snapcraft"
      - name: Install the snap
        run: sudo snap install --dangerous xteve*.snap
      - name: Wait for service startup
        run: sleep 10
      - name: Check service status and dump logs
        run: |
          echo "--- Checking xteve service status ---"
          snap services xteve
          echo "--- Dumping xteve service logs ---"
          sudo snap logs xteve || echo "No logs yet or logs not accessible"
          echo "--- Verifying xteve service is active ---"
          snap services xteve | grep -E "^xteve\s+.*active"
